### PR TITLE
reviewers.md: latest updates

### PR DESCRIPTION
**Pull request by rshym**
Add new repos:
- .github
- lisot
- meta-xt-prod-devel-rpi5
- meta-xt-prod-devel-sa8155p
- meta-xt-qcom
- meta-xt-rpi5
- zephyr-xrun

### CODE REVIEW

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

@firscity, @oleksiimoisieiev, @GrygiriiS, @dterletskiy, we need your acked-by tags as well.

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by oleksiimoisieiev** [comment]
LGTM `Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Comment by dterletskiy** [comment]
Acked-by: Dmytro Terletskyi <dmytro_terletskyi@epam.com>

**Comment by GrygiriiS** [comment]
`Acked-by: Grygorii Strashko <grygorii_strashko@epam.com>`

**Comment by rshym** [comment]
All `Acked-by` are added.
Ready to be merged.

**Pull request merged**
