### PR TITLE
Add rules for branches and releases

### PR DESCRIPTION
**Pull request by rshym**
Describe some rules for the xen-troops repos:
- the usage of the branches
- the naming of the branches
- the fixing of the releases
- the naming of the release tags

### CODE REVIEW

**Review by lorc — COMMENTED** [review]
I have no comments regarding the contents, but I think we need to separate this document into two: one about branch (and maybe tag) naming and another one - about releasing process.

Also, looks like we need some coding style regarding markdown files. At least we need to limit line length to some sensible value like 80-100 characters.

**Comment by rshym** [comment]
> I think we need to separate this document

Done.

> we need to limit line length to some sensible value like 80-100 characters.

Sorry, I forgot. Fixed.

**Review by lorc — APPROVED** [review]
Sorry for the late review

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added.
Ready to be merged.

**Pull request merged**
