### PR TITLE
Move Wiki from prod-devel

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by rshym** [comment]
Result can be seen at https://rshym.github.io/wiki

**Comment by lorc** [comment]
Thanks. This is a good job. But, this is not a wiki anymore. So I propose to rename "wiki" to "documentation". This applies to directory name and to mentions in text.

**Comment by lorc** [comment]
Thanks!

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
Ack is added.
Ready to be merged

**Pull request merged**
